
esphome:
  name: arrosage-1
  friendly_name: Arrosage_1

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key" # change it

ota:
  password: "password" # change it

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "password" # change it

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO2
    inverted: True

# x1 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO5
    name: Relay1
    id: relay1

# Temperature and humidity
sensor:
  - platform: dht
    pin: GPIO13
    temperature:
      name: "Plant environement Temperature"
    humidity:
      name: "Plant environement Humidity"
    update_interval: 10s
    model: AM2302
  - platform: adc
    pin: GPIO17
    name: "Soil humidity"
    icon: "mdi:water-percent"
    device_class: "moisture"
    state_class: "measurement"
    update_interval: 0.2s
    accuracy_decimals: 1
    unit_of_measurement: " V"
    filters:
      - sliding_window_moving_average: # averages the last 10 results, probably overkill
          window_size: 5
          send_every: 5
      - lambda: |-
          if (x > 0.8) {
            return 0;
          } else if (x < 0.35) {
            return 100;
          } else {
            return (0.8-x) / (0.8-0.35) * 100.0;
          }