esphome:
  name: esp32-cam-1
  friendly_name: esp32-cam_1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key" # change it

ota:
  password: "password" # change it

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "password" # change it

captive_portal:
    

esp32_camera:
  name: ESP32 Cam
  internal: true     #<-- set to 'false' only if you don't want to use Frigate
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1280x1024
  jpeg_quality: 10
  agc_mode: auto
  agc_gain_ceiling: 4x
  wb_mode: auto
  vertical_flip: false      #<-- you can cange this if you need
  horizontal_mirror: true  #<-- you can cange this if you need

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: gpio
    pin: GPIO4
    name: "Flash"